# Generated by Django 3.2.14 on 2023-05-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images/images'),
        ),
    ]
