# Generated by Django 3.2.14 on 2023-05-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0006_auto_20230516_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivered',
            field=models.CharField(default='Not deliverd', max_length=100),
        ),
    ]
