# Generated by Django 3.2.14 on 2023-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0007_alter_orders_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='generic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
