# Generated by Django 3.2.14 on 2023-05-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0008_product_generic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivered',
            field=models.CharField(default='Not delivered', max_length=100),
        ),
    ]
