# Generated by Django 3.2.14 on 2023-05-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0009_alter_orders_delivered'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
