# Generated by Django 3.2.14 on 2023-05-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0011_alter_orders_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
    ]
